package icu.mhb.mybatisplus.plugln.constant;

/**
 * 常用常量
 *
 * @author mahuibo
 * @Title: JoinConstant
 * @time 8/27/21 3:50 PM
 */
public final class JoinConstant {

    private JoinConstant() {
    }

    public static final String GENERATION_DESC = "/** \n" +
            " * This file is automatically generated, please do not modify it manually \n" +
            " * generation tool：mybatis-plus-join \n" +
            " * author：mahuibo \n" +
            " */ \n";

    public static final String GENERATION_BASE_MODEL_NAME = "BaseChainModel";

    public static final String ALIAS = "alias";

    public static final String BUILD_CHAIN_FIELD_DATA = "buildChainFieldData";

    public static final String CHAIN_FIELD_DATA = "ChainFieldData";

    public static final String SET_ENTITY = "setEntity";

    public static final String CHAIN_FIELD_DATA_PACKAGE = "import icu.mhb.mybatisplus.plugln.entity.ChainFieldData;";

    public static final String BASE_CHAIN_MODEL_PACKAGE = "import icu.mhb.mybatisplus.plugln.entity.BaseChainModel;";

    /**
     * join SQL片段xml名称
     */
    public static final String JOIN_SQL_NAME = "${ew.joinSql}";

    /**
     * 表别名 SQL片段 xml名称
     */
    public static final String TABLE_ALIAS_NAME = "${ew.masterTableAlias}";

    /**
     * as关键字
     */
    public static final String AS = "%s AS %s";

    /**
     * mybatis plus 参数名字
     */
    public static final String MP_PARAMS_NAME = "ew.paramNameValuePairs";

    /**
     * mapper class参数名
     */
    public static final String CLASS_PARAMS_NAME = "returnClassType0000000001111";

    public static final String DEFAULT_JOIN_TABLE_NAME = "DEFAULT_JOIN_TABLE_NAME";
}
